### ISSUE TITLE
How to switch to MS SQL Server database

### ISSUE THREAD

**Issue by pengxiaobo123** [blogifierdotnet/Blogifier.SPA#4]
{
  "Blogifier": {
    "DbProvider": "MS SQL Server",
    "ConnString": "Data Source=localhost;Initial Catalog=BlogDb;Persist Security Info=True;User ID=sa;Password=sa",

    "Avatar": "lib/img/avatar.jpg",
    "DemoMode": false,
    "ImageExtensions": "png,jpg,jpeg,gif,bmp,tiff",
    "ImportTypes": "zip,7z,xml,pdf,doc,docx,xls,xlsx,mp3,avi",
    "SeedData": false,

    "SendGridApiKey": "YOUR-SENDGRID-API-KEY",
    "SendGridEmailFrom": "admin@blog.com",
    "SendGridEmailFromName": "Blog admin",

    "GithubRepoUrl": "https://api.github.com/repos/blogifierdotnet/Blogifier/releases/latest"
  }
}
I've tried to change it to this, it's useless. It's a direct error

引发的异常:“System.ArgumentException”(位于 Microsoft.Data.Sqlite.dll 中)
引发的异常:“System.ArgumentException”(位于 Microsoft.Data.Sqlite.dll 中)
引发的异常:“System.ArgumentException”(位于 System.Data.Common.dll 中)
引发的异常:“System.ArgumentException”(位于 System.Data.Common.dll 中)
“iisexpress.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.4\System.Diagnostics.StackTrace.dll”。
“iisexpress.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.4\System.Reflection.Metadata.dll”。
Microsoft.EntityFrameworkCore.Query: Error: An exception occurred while iterating over the results of a query for context type 'Blogifier.Core.Data.AppDbContext'.
System.ArgumentException: Keyword not supported: 'initial catalog'.
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.GetIndex(String keyword)
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.set_Item(String keyword, Object value)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder..ctor(String connectionString)
   at Microsoft.Data.Sqlite.SqliteConnection.set_ConnectionString(String value)
   at Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteRelationalConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.CreateCommand(RelationalCommandParameterObject parameterObject, Guid commandId, DbCommandMethod commandMethod)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Microsoft.EntityFrameworkCore.Storage.Internal.NoopExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()

System.ArgumentException: Keyword not supported: 'initial catalog'.

**Comment by rxtur** [comment]
Try this as connection string (`SqlServer` is a keyword)
```js
{
  "Blogifier": {
    "DbProvider": "SqlServer",
    "ConnString": "Server=.\\SQLEXPRESS;Database=Blogifier;Trusted_Connection=True",
    ...
  }
}
```
[from here](https://github.com/blogifierdotnet/Blogifier/blob/master/docs/SqlServer.md)
